//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4_BAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARMAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BARMAN()
        {
            this.SURPLACE = new HashSet<SURPLACE>();
        }
    
        public int ID_USER { get; set; }
        public int ID_BAR { get; set; }
        public Nullable<bool> ESTDIRIGEANT { get; set; }
        public Nullable<System.DateTime> DATE_ARRIVER { get; set; }
        public Nullable<System.DateTime> DATE_DEPART { get; set; }
        public Nullable<bool> ESTBARMAN { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string MAIL { get; set; }
        public string MDP { get; set; }
    
        public virtual BARS BARS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SURPLACE> SURPLACE { get; set; }
    }
}
