//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4_BAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BARS()
        {
            this.BARMAN = new HashSet<BARMAN>();
            this.STOCKER = new HashSet<STOCKER>();
            this.COMMANDE = new HashSet<COMMANDE>();
        }
    
        public int ID_BAR { get; set; }
        public int ID_TYPE { get; set; }
        public string PHOTOBAR { get; set; }
        public string NOMBAR { get; set; }
        public Nullable<System.TimeSpan> OUVERTURE { get; set; }
        public Nullable<System.TimeSpan> FERMETURE { get; set; }
        public string ADRESSE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BARMAN> BARMAN { get; set; }
        public virtual TYPEBAR TYPEBAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKER> STOCKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDE { get; set; }
    }
}
