//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4_BAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        public int ID_USER { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string MAIL { get; set; }
        public string MDP { get; set; }
    }
}
