//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4_BAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_access_tokens
    {
        public decimal id { get; set; }
        public string tokenable_type { get; set; }
        public decimal tokenable_id { get; set; }
        public string name { get; set; }
        public string token { get; set; }
        public string abilities { get; set; }
        public Nullable<System.DateTime> last_used_at { get; set; }
        public Nullable<System.DateTime> expires_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
