//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP4_BAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_stats_commande_emporter_plus
    {
        public int ID_PRODUIT { get; set; }
        public string NOM_PRODUIT { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
